export default [
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        customElements: "readonly",
        HTMLElement: "readonly",
        CSS: "readonly",
        fetch: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        MutationObserver: "readonly",
        localStorage: "readonly",
        getComputedStyle: "readonly",
        Blob: "readonly",
        URL: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        FileReader: "readonly",
        navigator: "readonly",
        history: "readonly",
        CustomEvent: "readonly",
        module: "readonly",
        PREDEFINED_THEMES: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
      "no-console": "off",
      "semi": ["error", "always"],
      "no-var": "error",
      "prefer-const": "warn",
    },
  },
];